In [30]:
import copy
from typing import List
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import serpentTools
from serpentTools.parsers.results import ResultsReader

res1 = serpentTools.read(str("05_BUstep_calc_comp_4_natU_99N15/01_5000d_non_discrete/wh_lfr_res.m"))
dep1 = serpentTools.read(str("05_BUstep_calc_comp_4_natU_99N15/01_5000d_non_discrete/wh_lfr_dep.m"))

res2 = serpentTools.read(str("05_BUstep_calc_comp_4_natU_99N15/02_5000d_discrete/wh_lfr_res.m"))
dep2 = serpentTools.read(str("05_BUstep_calc_comp_4_natU_99N15/02_5000d_discrete/wh_lfr_dep.m"))
total1 = dep1.materials['total']
total2 = dep2.materials['total']

SERPENT Serpent 2.1.33 found in 05_BUstep_calc_comp_4_natU_99N15/01_5000d_non_discrete/wh_lfr_res.m, but version 2.1.31 is defined in settings
  Attemping to read anyway. Please report strange behaviors/failures to developers.
SERPENT Serpent 2.1.33 found in 05_BUstep_calc_comp_4_natU_99N15/02_5000d_discrete/wh_lfr_res.m, but version 2.1.31 is defined in settings
  Attemping to read anyway. Please report strange behaviors/failures to developers.
Executing <Task pending coro=<Kernel.dispatch_queue() running at /misc/home/stalex/01_work/01_wh_lfr/.direnv/python-3.7.13/lib/python3.7/site-packages/ipykernel/kernelbase.py:510> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x2ba71132f600>()] created at /misc/home/stalex/01_work/01_wh_lfr/.direnv/python-3.7.13/lib/python3.7/site-packages/tornado/queues.py:248> cb=[IOLoop.add_future.<locals>.<lambda>() at /misc/home/stalex/01_work/01_wh_lfr/.direnv/python-3.7.13/lib/python3.7/site-packages/tornado/ioloop.py:687] created at /mis

In [29]:
#dep1.materials.keys()
total1.data.keys()
dep1.zais
depl1.plot('burnup', 'adens', zai=[942410, 942411]);

[922340,
 922350,
 922360,
 922380,
 932370,
 942380,
 942390,
 942400,
 942410,
 942420,
 952410,
 952430,
 420990,
 430990,
 441010,
 451030,
 471090,
 551330,
 621470,
 621490,
 621500,
 621510,
 621520,
 601430,
 601450,
 631530,
 641550,
 666,
 0]

In [6]:
sorted(res1.resdata.keys())

['absKeff',
 'absKinf',
 'actinideActivity',
 'actinideDecayHeat',
 'actinideIngTox',
 'actinideInhTox',
 'adjIfpAnaBetaEff',
 'adjIfpAnaLambda',
 'adjIfpGenTime',
 'adjIfpImpBetaEff',
 'adjIfpImpLambda',
 'adjIfpLifetime',
 'adjIfpRossiAlpha',
 'adjMeulekampBetaEff',
 'adjMeulekampLambda',
 'adjNauchiBetaEff',
 'adjNauchiGenTime',
 'adjNauchiLambda',
 'adjNauchiLifetime',
 'adjPertBetaEff',
 'adjPertGenTime',
 'adjPertLifetime',
 'adjPertRossiAlpha',
 'albedoLeakrate',
 'allocMemsize',
 'alphaDecaySource',
 'anaAfge',
 'anaAlf',
 'anaDelayedEmtime',
 'anaEalf',
 'anaInvSpd',
 'anaKeff',
 'anaMeanNcol',
 'anaSlowTime',
 'anaThermFrac',
 'anaThermTime',
 'availMem',
 'avgRealCol',
 'avgSurfCross',
 'avgTrackingLoops',
 'avgTracks',
 'avgVirtCol',
 'balaLossNeutronCapt',
 'balaLossNeutronCut',
 'balaLossNeutronErr',
 'balaLossNeutronFiss',
 'balaLossNeutronLeak',
 'balaLossNeutronTot',
 'balaNeutronDiff',
 'balaSrcNeutronFiss',
 'balaSrcNeutronNxn',
 'balaSrcNeutronSrc',
 'balaSrcNeutron

In [31]:
res1["absKeff"], res1["burnup"], #res1["burnDays"]

(array([[2.38178e-01, 4.40000e-04],
        [4.86450e-01, 3.10000e-04],
        [8.07016e-01, 2.50000e-04],
        [8.87350e-01, 2.40000e-04],
        [9.03563e-01, 2.30000e-04],
        [8.94265e-01, 2.20000e-04]]),
 array([[  0.     ,   0.     ],
        [  2.78949,   2.78959],
        [ 13.9475 ,  13.9477 ],
        [ 33.4739 ,  33.4742 ],
        [ 69.7373 ,  69.7377 ],
        [139.475  , 139.475  ]]))

In [4]:
res2["absKeff"], res2["burnup"]

(array([[2.38873e-01, 4.20000e-04],
        [2.39455e-01, 4.00000e-04],
        [2.40864e-01, 4.30000e-04],
        [2.48178e-01, 4.20000e-04],
        [2.64714e-01, 3.90000e-04],
        [3.04143e-01, 3.60000e-04],
        [3.45534e-01, 3.60000e-04],
        [4.02508e-01, 3.60000e-04],
        [4.93672e-01, 3.20000e-04],
        [5.48608e-01, 2.90000e-04],
        [6.81131e-01, 2.70000e-04],
        [7.46295e-01, 2.70000e-04],
        [7.85969e-01, 2.70000e-04],
        [8.11372e-01, 2.50000e-04],
        [8.30382e-01, 2.60000e-04],
        [8.60390e-01, 2.40000e-04],
        [8.74430e-01, 2.40000e-04],
        [8.81478e-01, 2.40000e-04],
        [8.83911e-01, 2.30000e-04],
        [8.86297e-01, 2.30000e-04],
        [8.86587e-01, 2.30000e-04],
        [8.86132e-01, 2.20000e-04],
        [8.84854e-01, 2.30000e-04],
        [8.83976e-01, 2.20000e-04],
        [8.82593e-01, 2.20000e-04],
        [8.81548e-01, 2.30000e-04]]),
 array([[0.00000e+00, 0.00000e+00],
        [2.79446e-02, 2.79